name: SafeGuard2
main: io.github.m1enkrafftman.SafeGuard2.SafeGuard2
version: ${project.version}

author: m1enkrafft_man
website: http://m1enkrafftman.github.io/SafeGuard2/

commands:
    safeguard:
        description: SafeGuard command set.
        aliases: [sg]
        usage: /safeguard