package io.github.m1enkrafftman.SafeGuard2.checks;

public enum SGCheckTag {
	
	MOVEMENT_SPEED, MOVEMENT_SNEAK, MOVEMENT_FLIGHT, MOVEMENT_INVALID,
	
	BLOCKBREAK_REACH,
	
	BLOCKPLACE_REACH,
	
	COMBAT_SELFHIT;

}
