package io.github.m1enkrafftman.safeguard2.checks;

public enum SGCheckTag {
	
	MOVEMENT_SPEED, MOVEMENT_SNEAK, MOVEMENT_FLIGHT, MOVEMENT_INVALID,
	MOVEMENT_WATER, MOVEMENT_VERTICAL,
	
	BLOCKBREAK_REACH,
	
	BLOCKPLACE_REACH, BLOCKPLACE_SPEED,
	
	COMBAT_SELFHIT, COMBAT_SPEED, COMBAT_POSTMORTEM, COMBAT_REACH;

}
